proyecto_osin/accounts/urls.py
from django.urls import path
from .views import signup, login_view, logout_view

app_name='accounts'

urlpatterns = [
    path('signup',signup,name="signup"),
    path('login',login_view,name="login"),
    path('logout',logout_view,name="logout")
]

proyecto_osin/proyecto_osin/urls.py
from django.contrib import admin
from django.urls import path, include
from .routers import router
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('asignacion/', include('buscador.urls')),
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('search/',include('search.urls')),
    path('accounts/',include('accounts.urls')),
    path('persona/',include('persona.urls')),
    path('reporte/',include('reporte.urls')),
    path('roles/',include('roles.urls')),
    # TemplateView.as_view(template_name='persona.html')
    #path('persona/',view=TemplateView.as_view(template_name='persona.html')),
    path('api/', include(router.urls))
]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyecto_osin/roles/urls.py
from django.urls import path
from .views import listroles, adduser


urlpatterns = [
         path('', listroles,name='listroles'),
         path('adduser',adduser,name='adduser'),
]

proyecto_osin/templates/footer.html
{% comment %}
<footer>
    <div class="pull-right">
        OSINT - TODOS LOS DERECHOS RESERVADOS
    </div>
    <div class="clearfix"></div>
</footer> {% endcomment %}

proyecto_osin/templates/layout.html
<!DOCTYPE html> {% load staticfiles %}
<html lang="es">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col menu_fixed">
                <div class="left_col scroll-view">
                    {% include 'sidebar-profile.html' %} {% include 'side-bar.html' %}
                </div>
            </div>
            {% include 'top-nav.html' %}
            <div class="right_col" role="main" id="app">
                <div class="page-title">
                    {% csrf_token %} {% block content %}{% endblock %}
                </div>
            </div>
            {% include 'footer.html' %}
        </div>
    </div>

    <script src="{% static 'public/bundle.js' %}"></script>


    {% block script %}{% endblock %}

</body>

</html>

proyecto_osin/templates/side-bar.html
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
            {% comment %}
            <li><a><i class="fa fa-home"></i> Inicio <span class="fa fa-chevron-down"></span></a></li>
            {% endcomment %}

            <li><a href="{% url 'list_auto' %}"><i class="fa fa-search"></i> Busqueda redes <span
                        class="fa fa-chevron-down"></span></a></li>
            <li><a href="{% url 'listpersona' %}"><i class="fa fa-search"></i> Sentimiento <span
                        class="fa fa-chevron-down"></span></a></li>

            {% comment %}
            <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a></li>
            <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a></li>
            <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a></li>
            <li><a><i class="fa fa-clone"></i>Layoutsx2 <span class="fa fa-chevron-down"></span></a></li>
            <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="#">Chart JS</a></li>
                    <li><a href="#">Chart JS2</a></li>
                </ul>
            </li> {% endcomment %}
        </ul>
    </div>
</div>

proyecto_osin/templates/sidebar-profile.html
<div class="clearfix"></div>

<div class="profile clearfix">
    {% comment %}
    <div class="profile_pic">
        <img src="/media/img.jpg" alt="..." class="img-circle profile_img">
    </div> {% endcomment %}
    <div class="prod_title" style="margin-left:15px;">

    </div>
</div>

proyecto_osin/templates/top-nav.html
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        {% if user.is_authenticated %}
                            <img src="/media/img.jpg" alt="">{{ user.username }}
                            {% else %}
                            <img src="/media/img.jpg" alt="">
                            {% endif %}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li>
                            <form action="{% url 'accounts:logout' %}" method="post" class="formLogout">
                                {% csrf_token %}
                                <button type="submit" class="btn"> <i class="fa fa-sign-out"></i> Salir</button>
                            </form>

                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>