proyecto_osin/accounts/urls.py
from django.urls import path
from .views import signup, login_view, logout_view

app_name='accounts'

urlpatterns = [
    path('signup',signup,name="signup"),
    path('login',login_view,name="login"),
    path('logout',logout_view,name="logout")
]

proyecto_osin/proyecto_osin/urls.py
from django.contrib import admin
from django.urls import path, include
from .routers import router
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('asignacion/', include('buscador.urls')),
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('search/',include('search.urls')),
    path('accounts/',include('accounts.urls')),
    path('persona/',include('persona.urls')),
    path('reporte/',include('reporte.urls')),
    path('roles/',include('roles.urls')),
    # TemplateView.as_view(template_name='persona.html')
    #path('persona/',view=TemplateView.as_view(template_name='persona.html')),
    path('api/', include(router.urls))
]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyecto_osin/roles/urls.py
from django.urls import path
from .views import listroles, adduser


urlpatterns = [
         path('', listroles,name='listroles'),
         path('adduser',adduser,name='adduser'),
]

proyecto_osin/accounts/models.py
from django.db import models

# Create your models here.

proyecto_osin/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm 
from django import forms


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30, 
                               widget=forms.TextInput(attrs={'type':'text','class': 'form-control', 'name': 'username','autocomplete':'off'}))
    password = forms.CharField(label="Password", max_length=30, 
                               widget=forms.TextInput(attrs={'type':'password','class': 'form-control', 'name': 'password'}))

proyecto_osin/accounts/views.py
from django.shortcuts import render,redirect
import requests
from django.http import HttpResponse
from django.http import JsonResponse
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login, logout
from .forms import LoginForm
# Create your views here.
def signup(request):
    if (request.method=='POST'):
        form=UserCreationForm(request.POST)
        if (form.is_valid()):
            user=form.save()
            login(request,user)
            return redirect('list_auto')
    else:
        form=UserCreationForm()
        
    return render(request,'index.html',{'form':form})

def login_view(request):
    if (request.method=='POST'):
        form=LoginForm(data=request.POST)
        if (form.is_valid()):
            user=form.get_user()
            login(request,user)
            if request.user.is_authenticated:
                request.session["id_user"] = user.id
            return redirect('list_auto')
    else:
        form=LoginForm()
    
    return render(request,'login.html',{'form':form})

def logout_view(request):
    if (request.method=='POST'):
        del request.session['id_user']
        logout(request)
        return redirect('accounts:login')

proyecto_osin/accounts/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registrate</title>
</head>

<body>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %} {{form}}
        <button type="submit" class="btn btn-default">Entrar</button>
    </form>
</body>

</html>

proyecto_osin/accounts/templates/login.html
<!DOCTYPE html> {% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
    <title>Login</title>
</head>

<body>
    <div class="container">
        <br><br><br><br><br><br><br><br>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default log_in">
                    <div class="panel-heading titulo_login">

                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" id='form_login' action="{% url 'accounts:login' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Usuario:</label> {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label>Contraseña:</label> {{ form.password }}
                            </div>
                            <button class="btn btn-lg btn-success btn-block" type="submit"
                                name="login" />Entrar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>